---

- name: APT | Install PHP-FPM
  apt: pkg=php5-fpm state=latest

- name: LINEINFILE | PHP configuration
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^;?{{ item.key }}' line='{{ item.key }} = {{ item.value }}'
  with_items: php_ini
  notify: restart php-fpm

