---

- block:

  - name: APT | Install php-xdebug
    apt:
      pkg: "{{ php_package_prefix }}xdebug"
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: TEMPLATE | Deploy module configurations
    template:
      src: "etc/__php__/mods-available/xdebug.ini.j2"
      dest: "{{ php_mods_dir }}/xdebug.ini"
      owner: root
      mode: 0644
    notify: restart php-fpm

  when: php_install_xdebug

- name: APT | Uninstall php-xdebug
  apt:
    pkg: "{{ php_package_prefix }}xdebug"
    state: absent
  when: not php_install_xdebug
