---

- name: BLOCK | Install Xdebug
  when: php_install_xdebug
  block:
    - name: APT | Install xdebug
      ansible.builtin.apt:
        pkg: "{{ php_xdebug_package }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
        install_recommends: false
      when: ansible_os_family == 'Debian'

    - name: TEMPLATE | Deploy module configurations
      ansible.builtin.template:
        src: "etc/__php__/mods-available/xdebug.ini.j2"
        dest: "{{ php_mods_dir }}/xdebug.ini"
        owner: root
        mode: 0644
      notify: Restart php-fpm

- name: APT | Uninstall xdebug
  ansible.builtin.apt:
    pkg: "{{ php_xdebug_package }}"
    state: absent
  when: not php_install_xdebug
