---

- name: Restart php-fpm
  ansible.builtin.service:
    name: '{{ php_fpm_service }}'
    state: restarted
  when: php_install_fpm
  notify: Docker restart php-fpm

- name: Docker restart php-fpm  # noqa: command-instead-of-module no-changed-when
  ansible.builtin.command: 'service {{ php_fpm_service }} restart'
  when: ansible_virtualization_type == 'docker'
