---

platforms:
  - name: debian-11
    image: dokken/debian-11
    command: /lib/systemd/systemd
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: debian-11-php-8.0
    image: dokken/debian-11
    command: /lib/systemd/systemd
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true

provisioner:
  inventory:
    group_vars:
      all:
        __nginx_conf: /etc/nginx/nginx.conf
    host_vars:
      debian-11-php-8.0:
        php_version: '8.0'
