---

platforms:
  - name: debian-10
    image: dokken/debian-10
    command: /lib/systemd/systemd
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: debian-10-php-7.4
    image: dokken/debian-10
    command: /lib/systemd/systemd
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true

provisioner:
  inventory:
    group_vars:
      all:
        __nginx_conf: /etc/nginx/nginx.conf
    host_vars:
      debian-10-php-7.4:
        php_version: '7.4'
